version: "3.7"

services:
    app:
        build: .
        container_name: nuxt-app
        volumes:
            - .:/usr/src/nuxt-app
        restart: always
        ports:
            - "3000:3000"
        command: "npm run dev"
